[project]
name = "dipend-graph"
version = "0.0.0"
license = "Apache-2.0"
description = "A library for generating a DAG (Directed Acyclic Graph) of dependencies registered in Dipend's dependency container."
authors = [
  { name = "Saulo V. Alvarenga", email = "saulo.va@protonmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[project.urls]
Homepage = "https://github.com/saulova/py-dipend"
Documentation = "https://dipend.sauloalvarenga.dev.br"
Repository = "https://github.com/saulova/py-dipend"
Issues = "https://github.com/saulova/py-dipend/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"dipend_graph" = ["public/**"]
